pathsAVP
savename = 'R56F07_AOTU';
if ~exist('x') || ~ ( strcmp(x(1).Line,'R56F07-gal4') && strcmp(x(1).Area,'AOTu') )
    loadAVP
else, disp([savename ' objarray ''x'' already in workspace'])
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % Specific commands to run after loading objarray


% Some early experiments were run with the LED on throughout all experiments
% by mistake: make sure they're not included here:
x(find(~cellfun('isempty',strfind({x.Name},'LED ON')))) = [];

% Bad dark-spot in this fly, from trachea or similar above recording site
x(find(~cellfun('isempty',strfind({x.DateStr},'190612')) & ~cellfun('isempty',strfind({x.Name},'fly1'))  )) = [];

% Right hand side example
selectObj(1) = find(~cellfun('isempty',strfind({x.DateStr},'190612'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1808' )));
selectLayer(1) = 4;
% Right hand side, different fly, opposite tuning
selectObj(2) = find(~cellfun('isempty',strfind({x.DateStr},'181004'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1110' )));
selectLayer(2) = 4;
% Right hand side, different fly, opposite tuning
selectObj(3) = find(~cellfun('isempty',strfind({x.DateStr},'181004'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1141' )));
selectLayer(3) = 7;

% These objects had positive vertical pos / tuning correlations (over 0.15,p<0.05)
% selectSetPos = [ ...
selectSetPos = [ ...
    find(~cellfun('isempty',strfind({x.DateStr},'190607'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1301' ))), ...
    find(~cellfun('isempty',strfind({x.DateStr},'190607'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1248' ))), ...
    find(~cellfun('isempty',strfind({x.DateStr},'190607'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1339' ))), ...
    find(~cellfun('isempty',strfind({x.DateStr},'190607'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1817' ))), ...
    find(~cellfun('isempty',strfind({x.DateStr},'190607'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1810' ))), ...
    find(~cellfun('isempty',strfind({x.DateStr},'190612'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1650' ))), ...
    find(~cellfun('isempty',strfind({x.DateStr},'190612'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1634' ))), ...
    find(~cellfun('isempty',strfind({x.DateStr},'190612'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1808' ))), ...
    find(~cellfun('isempty',strfind({x.DateStr},'190604'))  &  ~cellfun('isempty',strfind({x.TimeStr},'2003' ))), ...
    find(~cellfun('isempty',strfind({x.DateStr},'181004'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1300' ))), ...
    ];


% These objects had negative vertical pos / tuning correlations (less than-0.15,p<0.05)
selectSetNeg = [ ...
    find(~cellfun('isempty',strfind({x.DateStr},'181004'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1141' ))), ...
    find(~cellfun('isempty',strfind({x.DateStr},'181004'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1212' ))), ...
    find(~cellfun('isempty',strfind({x.DateStr},'190606'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1213' ))), ...
    find(~cellfun('isempty',strfind({x.DateStr},'190607'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1710' ))), ...
    find(~cellfun('isempty',strfind({x.DateStr},'181004'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1110' ))), ...
    ];

selectSetOutliers = [ ...
    find(~cellfun('isempty',strfind({x.DateStr},'181004'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1247' ))), ...
    find(~cellfun('isempty',strfind({x.DateStr},'190612'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1904' ))), ...
      find(~cellfun('isempty',strfind({x.DateStr},'181001'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1052' ))), ...
   find(~cellfun('isempty',strfind({x.DateStr},'190606'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1122' ))), ...
      find(~cellfun('isempty',strfind({x.DateStr},'190606'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1236' ))), ...
    ];
selectSetTuTuCompare = [ ...
    find(~cellfun('isempty',strfind({x.DateStr},'190612'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1816' ))), ...
    find(~cellfun('isempty',strfind({x.DateStr},'190612'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1910' ))), ... 
      find(~cellfun('isempty',strfind({x.DateStr},'190607'))  &  ~cellfun('isempty',strfind({x.TimeStr},'1710' ))), ...
];